version: '3.5'

services:
  data:
    container_name: data
    restart: always
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data 
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"