# Generated by Django 4.2.7 on 2023-12-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('room_count', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('tv', models.BooleanField()),
                ('fridge', models.BooleanField()),
                ('bed_count', models.IntegerField()),
                ('category', models.CharField(choices=[('звичайний', 'Звичайний'), ('полу люкс', 'Полу Люкс'), ('люкс', 'Люкс')], default='звичайний', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_code', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('stay_days', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.room')),
            ],
        ),
    ]
